apiVersion: v1
kind: Service
metadata:
 name: deployment-service
 labels:
  name: deployment-service
  app: 
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
 selector:
  app: myweb
  